#!/bin/bash
source .config/dm-script.conf

    browser=$(cat $HOME/.config/qtile/config.py | grep BROWSER | awk '{print $3}'  )



#Readssites from qutebrowsers quickmark tab
list=$(cat ~/.config/qutebrowser/quickmarks | sed -e "s/^/(/g" -e "s/ /) /g" )



choice=$(printf '%s\n' $list | xargs -n2 | run -p "Open Website:")



[ -z "$choice"  ] && exit



list=$(echo $choice | awk '{print $NF}') 


#Opening website
$browser $list




