#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Script that will open applications of my choice
# using rofi or wofi
source $HOME/.config/dm-script.conf


# set options in dm-script.conf
declare -a options=(

$applications

)


appimage=$(find /opt $HOME/Applications -iname "*.Appimage")


choice=$(printf '%s\n' "${options[@]}" "${appimage[@]}" | run  -p "Open App:"  )


 [ -z $choice ] && exit



$choice





