#!/bin/bash 
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-display-font
# Description: Dm script to display fonts installed on the system
# Author: Karl Fredin

# source all the configuration
source $HOME/.config/dm-script.conf

# stores all the fonts in list
list=$(ls -d /usr/share/fonts/*/* | grep -v fonts.dir | grep -v fonts.scale)

# make you choice
choice=$(printf '%s\n' "${list[@]}" | cut -d '/' -f 5,6 | run "Font " )

# exit if you made no choice
[ -z $choice ] && exit

# make the full path
create_proper_path="/usr/share/fonts/$choice"

# displays the font using display
display $create_proper_path 
