#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\

# Imports the configuration
source $HOME/.config/dm-script.conf

# Choose the config files you want quick access to
# Just add them in the array with this format "NAME - path_to_file"
# This is files for your regular user
declare -A files

files[abbr]="$HOME/.config/fish/conf.d/abbr.fish"
files[alacritty]="$HOME/.config/alacritty/alacritty.yml"
files[alias]="$HOME/.config/alias-zsh-bash"
files[awesome]="$HOME/.config/awesome/rc.lua"
files[awesome autostart]="$HOME/.config/awesome/autostart.sh"
files[bash]="$HOME/.bashrc"
files[conky]="$HOME/.config/conky/main"
files[dm editconfig]="$HOME/.dmenu/dm-editconfig"
files[dm script.conf]="$HOME/.config/dm-script.conf"
files[dmenu]="$HOME/.dmenu"
files[doom config]="$HOME/.config/doom/README.org"
files[doom packages]="$HOME/.config/doom/packages.el"
files[doom init]="$HOME/.config/doom/init.el"
files[dunst]="$HOME/.config/dunst/dunstrc"
files[fish]="$HOME/.config/fish/config.fish"
files[hyprland]="/home/karl/.config/hypr/README.org"
files[kitty]="$HOME/.config/kitty/kitty.conf"
files[kitty theme]="$HOME/.config/kitty/theme.conf "
files[language script]="$HOME/myrepos/languagelearning/main.sh"
files[mutt]="$HOME/.config/mutt/muttrc"
files[ncspot]="$HOME/.config/ncspot/config.toml"
files[nvim]="$HOME/.config/nvim/init.vim"
files[nvim plugins]="$HOME/.config/nvim/vim-plug/plugins.vim"
files[fish]="$HOME/.config/fish/config.fish"
files[pcmanfm]="$HOME/.config/pcmanfm/default/pcmanfm.conf"
files[picom]="$HOME/.config/picom/picom.conf"
files[picom jona]="$HOME/.config/picom/picom-jona.conf"
files[script]="$HOME/.scripts"
files[sync script]="$HOME/.scripts/sync/sync-script.org"
files[qtile]="$HOME/.config/qtile/config.py"
files[qtile autostart]="$HOME/.config/qtile/autostart.sh"
files[qutebrowser config]="$HOME/.config/qutebrowser/config.py"
files[qutebrowser quickmarks]="$HOME/.config/qutebrowser/quickmarks"
files[rofi themes user]="$HOME/.config/rofi/themes"
files[rtorrent]="$HOME/.rtorrent.rc"
files[starship]="$HOME/.config/starship.toml"
files[tmux]="$HOME/.tmux.conf.local"
files[vieb]="$HOME/.config/Vieb/viebrc"
files[vifm]="$HOME/.config/vifm/vifmrc"
files[vifm colors]="$HOME/.config/vifm/colors"
files[waybar config]="$HOME/.config/waybar/config.jsonc"
files[waybar style]="$HOME/.config/waybar/style.css"
files[wlogout layout]="$HOME/.config/wlogout/layout"
files[wlogout style]="$HOME/.config/wlogout/style.css"
files[wofi config]="$HOME/.config/wofi/config"
files[wofi style]="$HOME/.config/wofi/style.css"
files[xmobar1]="$HOME/.config/xmobar/xmobarrc0"
files[xmobar2]="$HOME/.config/xmobar/xmobarrc1"
files[xmobar]="$HOME/.config/xmobar/"
files[xmonad]="$HOME/.xmonad/xmonad.hs"
files[zsh]="$HOME/.zshrc"
files[Yandex Disk]="$HOME/.config/yandex-disk/config.cfg"

# File that require root permission
# But it wont open these files as root
files[autofs auto]="/etc/autofs/auto.mnt"
files[autofs external]="/etc/autofs/external.mnt"
files[autofs master]="/etc/autofs/auto.master"
files[dunst]="/etc/dunst/dunstrc"
files[exports]="/etc/exports"
files[fstab]="/etc/fstab"
files[fish]="/etc/fish/config.fish"
files[grub]="/etc/default/grub"
files[host]="/etc/hosts"
files[lightdm webkit2]="/etc/lightdm/lightdm-webkit2-greeter.conf"
files[lightdm]="/etc/lightdm/lightdm.conf"
files[mutt wizard]="/usr/share/mutt-wizard/mutt-wizard.muttrc"
files[pacman]="/etc/pacman.conf"
files[sddm startup]="/usr/share/sddm/scripts/Xsetup"
files[rofi themes root]="/usr/share/rofi/themes"
files[logind]="/etc/systemd/logind.conf"

# I use print to format the array then I use sed to make the output cleaner
choice=$(printf '%s\n' "${!files[@]}" | sed -e 's/^\/*//g' -e '/-/d' -e '/^home/d' | run "Edit config file:" )

# Exit if you made no choice
[ -z "$choice" ] && exit

selection=$(printf '%s\n' "${files[${choice}]}" )

exec $GUI_EDITOR $selection



