#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-editconfig
# Description: Dm script to open various files on the system so you can quickly edit them
# Author: Karl Fredin

# Imports the configuration
source $HOME/.config/dm-script.conf

# Variables for my git repos
DOTFILES_REPO_PATH="$HOME/myrepos/dotfiles"
DMSCRIPTS_REPO_PATH="$HOME/myrepos/dmscripts"


# Making the array as you can see I dont add that many 
# files/folders cause I don't wanna edit this script that much
declare -A files


# Scripts
files[$HOME/.dmenu]="$DMSCRIPTS_REPO_PATH/.dmenu"
files[$HOME/.scripts]="$DOTFILES_REPO_PATH/.scripts"

# config files but it will only grabe configs I have in my dotfiles repo
files[$HOME/.config]="$DOTFILES_REPO_PATH/.config"

# Yandex disk
files[$HOME/.config/yandex-disk]="$HOME/.config/yandex-disk"

#files[$HOME/.xmonad]="$DOTFILES_REPO_PATH/.xmonad"

# dm script config
files[$HOME/.config/dm-script.conf]="$DMSCRIPTS_REPO_PATH/.config/dm-script.conf"

# zshrc
files[$HOME/.zshrc]="$DOTFILES_REPO_PATH/.zshrc"

# bashrc
files[$HOME/.bashrc]="$DOTFILES_REPO_PATH/.bashrc"

# tmux
files[$HOME/.tmux.conf.local]="$DOTFILES_REPO_PATH/.tmux.conf.local"

# etc
files[/etc]="/etc"

# if you use -g then it will generate a cache file
# which is a most otherwise this script is slow
# if you use -t the script will use fzf in the terminal
while getopts ":gt" opt; do
  case $opt in
     g)
      GENERATE=true
      ;;
     t)
      FZF='y'
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      echo "Enter -g to regenerate the cache file" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# generates the cache file
if [ "$GENERATE" = "true" ] ; then

echo "Generating Cache file"

for MY_FILES in $(printf '%s\n' "${files[@]}") ; do
        

   if [ -d $MY_FILES ] ; then

       for MY_FILES_LOOP in $(find  $MY_FILES/* -type f 2> /dev/null ) ; do

           SAVE=$(echo "$MY_FILES_LOOP" | sed -e "s|$DOTFILES_REPO_PATH|$HOME|" -e "s|$DMSCRIPTS_REPO_PATH|$HOME|")

           FILES_TO_USE=$(echo "$SAVE" "$FILES_TO_USE")

       done
 
   elif [ -f $MY_FILES ] ; then    

       for MY_FILES_LOOP in $MY_FILES ; do

           SAVE=$(echo "$MY_FILES_LOOP" | sed -e "s|$DOTFILES_REPO_PATH|$HOME|" -e "s|$DMSCRIPTS_REPO_PATH|$HOME|")

           FILES_TO_USE=$(echo "$SAVE" "$FILES_TO_USE")

       done

   fi

done
        # outputs all files to the cache file, which is basically just a text file 
        # that contains paths to diffrent files I may want to edit
        [ -z "$FILES_TO_USE" ] || echo "$FILES_TO_USE" | xargs -n1 | grep -vw png > $HOME/.config/dm-editconfig-cache


else

       FILES_TO_USE=$(cat "$HOME/.config/dm-editconfig-cache")

       # if you use t flag for terminal the script will use fuzzy finder
       if [ "$FZF" = "y" ] ;then

         choice=$(printf '%s\n' "${FILES_TO_USE[@]}" | xargs -n1 | fzf )

         # Exit if you made no choice
         [ -z "$choice" ] && exit
   
         
         # runs using terminal editor
         $TUI_EDITOR "$choice"

       else

         choice=$(printf '%s\n' "${FILES_TO_USE[@]}" | xargs -n1 | run "Config Files " )

         # Exit if you made no choice
         [ -z "$choice" ] && exit
          
         # runs using graphical editor
         $GUI_EDITOR "$choice"
       fi

fi
