#!/bin/bash
##____  _                      _
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  <
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# Name: dm-hub
# Description: Dm script that will list all my dm-scripts and then you can execute the script
# Author: Karl Fredin

# Script that will list all my dmscripts
# and then you can run your script of choice

# Source all dmscripts configs
source $HOME/.config/dm-script.conf

# Define variables
DMENU_PATH=$HOME/.dmenu
DMENU_SCRIPT=$(ls $DMENU_PATH)

# Makes your choice
choice=$(printf '%s\n' "${DMENU_SCRIPT[@]}" | run -p "Run :" )

# Exit if no choice is made
[ -z $choice  ] && exit

# runs the choosen script
bash $choice
