#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-input
# Description: Dm script to change keyboardlayout
# Author: Karl Fredin

# Imports the configuration
source $HOME/.config/dm-script.conf

# declare all available layouts
declare -a options=(
"se"
"us"
"az"
)

# make your choice
choice=$(printf '%s\n' "${options[@]}" | run "Layout " )

# sets the layout of your choice
setxkbmap $choice
