#!/usr/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-man
# Description: Dm script to open man pages 
# Author: Karl Fredin

# Imports the configuration
source $HOME/.config/dm-script.conf

# Make your choice
choice=$( man -k . | awk '{ print $1 }' | sed 's/[A-Z]/\L&/g' | run -p "Choose MAN page: ")

# opens the man pages in choosen pdf viewer
man -Tpdf $choice | $PDF_VIEWER -

