#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-openweb
# Description: Dm script to open a wesbite from my url list
# Author: Karl Fredin

# Source the dm-script config
source $HOME/.config/dm-script.conf

# Reads websites from my URL variable
# Configure this in the dm-script config file
LIST=$(cat $URL | sed -e "s/^/(/g" -e "s/ /) /g" )

# make the choice
choice=$(printf '%s\n' $LIST | xargs -n2 | run -p "Open Website:")

# exit if choice is empty
[ -z "$choice"  ] && exit

# makes the url
LIST=$(echo $choice | awk '{print $NF}') 

# Opening your choice
$BROWSER $LIST




