#!/usr/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-play-pause
# Description: Dm script to pause play media
# Author: Karl Fredin

# Source the config file
source $HOME/.config/dm-script.conf


check_back="back"
while [ $check_back = "back" ] ; do
 
players=$(playerctl -l)

choice=$( echo $players "exit" | xargs -n1 | run "Choose Instance To Control: " )

[ -z $choice ] && exit

[ $choice = "exit" ] && exit

while true ; do

play_pause=$( printf "play\npause\nnext\nprevious\nback\nexit" | run "Action ")

check_back="$play_pause"

[ $play_pause = "exit" ] && exit
[ $play_pause = "back" ] && break

playerctl $play_pause -p $choice

done
done
