#!/usr/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-pdfview
# Description: Dm script to open pdf files on the ssystem
# Author: Karl Fredin

# Imports the configuration
source $HOME/.config/dm-script.conf

# make your choice
choice=$( find $HOME/Yandex.Disk/ $HOME/.config  -iname "*.pdf"   | run "PDF file: " )

# exit if you made no choice
[ -z "$choice" ] && exit

# opens the pdf in choosen pdf viewer
$PDF_VIEWER "$choice"


