#!/bin/bash
##____  _                      _
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  <
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-search
# Description: Dm script to search the web
# Author: Karl Fredin


# Imports the configuration
source $HOME/.config/dm-script.conf


declare -a options=(

"Google"
"DuckDuckGo"
"Arch_Wiki"
"AUR"
"Wikipedia"
"YouTube"
"GreenManGaming"
"CDKeys"
"ProtonDB"
"GitHub"

)



choice=$( printf '%s\n' "${options[@]}" | run "Search Engine:")


[ -z $choice  ] && exit 

if [ $BROWSER = "qutebrowser" ] ; then

[ $choice = "Google" ] && choice=$(run  "Google:") && $BROWSER "!g $choice"
[ $choice = "DuckDuckGo" ] && choice=$(run  "DuckDuckGo:") && $BROWSER "$choice"
[ $choice = "Arch_Wiki" ] && choice=$(run  "Arch_Wiki:") && $BROWSER "!aw $choice"
[ $choice = "AUR" ] && choice=$(run  "AUR:") && $BROWSER "!aur $choice"
[ $choice = "Wikipedia" ] && choice=$(run  "Wikipedia:") && $BROWSER "!w $choice"
[ $choice = "YouTube" ] && choice=$(run  "YouTube:") && $FULLSCREEN_BROWSER --new-window --app="https://www.youtube.com/results?search_query=$choice"
[ $choice = "GreenManGaming" ] && choice=$(run  "GMG:") && $BROWSER "https://www.greenmangaming.com/search?query=$choice"
[ $choice = "CDKeys" ] && choice=$(run  "CDKeys:") && $BROWSER "https://www.cdkeys.com/?q=$choice"
[ $choice = "ProtonDB" ] && choice=$(run  "ProtonDB:") && $BROWSER "https://www.protondb.com/search?q=$choice"
[ $choice = "GitHub" ] && choice=$(run  "GitHub:") && $BROWSER "https://github.com/search?q=$choice"



else

[ $choice = "DuckDuckGo" ] && choice=$(run "DuckDuckGo:") && $FULLSCREEN_BROWSER --new-window --app="https://duckduckgo.com/?q=$choice&t=h_&ia=web"
[ $choice = "YouTube" ] && choice=$(run "YouTube:") && $FULLSCREEN_BROWSER --new-window --app="https://www.youtube.com/results?search_query=$choice"
[ $choice = "Google" ] && choice=$(run "Google:") && $FULLSCREEN_BROWSER --new-window --app="https://www.google.com/search?q=$choice&sxsrf=AOaemvKtRfebj8eBmCWbIQAFyeRHUir_KA%3A1637602786126&source=hp&ei=4tWbYf_ABd7k2roPntifyAc&iflsig=ALs-wAMAAAAAYZvj8ge62gTjJ4BIRwCz9jCfO0SCwLBa&ved=0ahUKEwj_ueTiwaz0AhVeslYBHR7sB3kQ4dUDCAc&uact=5&oq=$choice&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgQIIxAnOgsILhCABBDHARCjAjoLCC4QgAQQxwEQ0QNQAFj_AWDXA2gAcAB4AIABkwGIAaUEkgEDMC40mAEAoAEB&sclient=gws-wiz"
[ $choice = "GreenManGaming" ] && choice=$(run "GMG:") && $FULLSCREEN_BROWSER --new-window --app="https://www.greenmangaming.com/search?query=$choice"
[ $choice = "CDKeys" ] && choice=$(run "CDKeys:") && $FULLSCREEN_BROWSER --new-window --app="https://www.cdkeys.com/?q=$choice"
[ $choice = "Arch_Wiki" ] && choice=$(run "Arch_wiki:") && $FULLSCREEN_BROWSER --new-window --app="https://wiki.archlinux.org/index.php?search=$choice&title=Special%3ASearch&go=Go"
[ $choice = "AUR" ] && choice=$(run "AUR:") && $FULLSCREEN_BROWSER --new-window --app="https://aur.archlinux.org/packages/?O=0&K=$choice"
[ $choice = "Wikipedia" ] && choice=$(run "Wikipedia:") && $FULLSCREEN_BROWSER --new-window --app="https://en.wikipedia.org/w/index.php?search=$choice&title=Special%3ASearch&go=Go&ns0=1"
[ $choice = "ProtonDB" ] && choice=$(run "ProtonDB:") && $FULLSCREEN_BROWSER --new-window --app="https://www.protondb.com/search?q=$choice"
[ $choice = "GitHub" ] && choice=$(run "GitHub:") && $FULLSCREEN_BROWSER --new-window --app="https://github.com/search?q=$choice"

fi






