#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-starship-theme
# Description: Dm script to change theme for starship prompt
# Author: Karl Fredin

# Imports the configuration
source $HOME/.config/dm-script.conf

# lists all you available themes
theme=$( ls $HOME/.config/starship-themes )

# kitty directory
export stardir=$HOME/.config

# make your choice 
choice=$(printf '%s\n' "${theme[@]}" | run "starship theme"   )

# exit if choice is empty
[ -z $choice ]  && exit

# removes current theme
unlink $stardir/starship.toml      

# updates the theme using a symlink
ln -s $HOME/.config/starship-themes/$choice $stardir/starship.toml




