#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-set-wallpaper
# Description: Dm script to change wallpaper in a standalone window manager
# Author: Karl Fredin

# you need sxiv installed for this script to work because
# that's what I use to set wallpaper togheter with feh or swaybg

# Imports the configuration
source $HOME/.config/dm-script.conf

# Sets variables
divider="---------"
exit="Exit"

# Creates the array that list all options
declare -a options=(
    "$HOME/Pictures/Wallpapers"
    "$HOME/Pictures/rose-pine"
    "$HOME/Pictures/Arch"
    "$HOME/Pictures/Nature/"
    "$HOME/Pictures/nord/"
    "$HOME/Pictures/Dracula/"
    "$HOME/Pictures/animation/"
)


# Main functions
list_wallpapers() {
# Removes all the directories that's empty from the option
for opt in "${options[@]}" ; do

    check_empty=$(ls "$opt"/* 2> /dev/null ) 
     
    [ -z "$check_empty" ] || wallpapers=$(printf '%s\n' "$wallpapers" "$opt")

done

# Sets the ooption available for the user
opt=$(printf '%s\n' "${wallpapers[@]}")

# Make your choice (choose your wallpaper directory)
choice=$(printf '%s\n' "${opt[@]}" |  $rofi_command )

# Case statement
case "$choice" in
        "" | "$divider")
            # exit if no option is chosen
            echo "No option chosen."
            ;;
        "$choice")
            
            # Makes the list of all the backgrounds in the choose directory
            # And Change background using sxiv if you choose
            ls -d "$choice"/* | sxiv -i

            list_wallpapers
            ;;
esac


# Exit if you make no choice
# [ -z "$choice" ] && exit

}

rofi_command=run


case "$1" in
    *)  # Run the main menu 
        list_wallpapers
        ;;
esac



