#!/bin/bash
##____  _                      _
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  <
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
# Name: dm-ssh
# Description: Dm script to open an ssh connection to my servers
# Author: Karl Fredin

# Script to easily connect to some of my servers

# Import the dmscript config
source $HOME/.config/dm-script.conf

# Configure your servers here
declare -a options=(

    "192.168.1.30"
    "192.168.1.31"

)

# make your choice here
choice=$(printf '%s\n' "${options[@]}" | run -p "Server to connect to: " )

# exit if you don't make a choice
[ -z $choice ] && exit


# connecting to the server
kitty -e ssh $USER_SSH@$choice
