#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# Name: dm-editconfig
# Description: dmenu script to delete or create snapshots using timeshift
# Author: Karl Fredin


# Source my custom settings
source $HOME/.config/dm-script.conf

# Constants
divider="---------"
goback="Back"
delete="Delete"
exit="Exit"

# Create snapshot 
create_snapshot() {
    sudo timeshift --create
}

# Deletes snapshot
delete_snapshot() {
    sudo timeshift --delete --snapshot "$1"
}

# Restore snapshot
restore_snapshot() {
    device=$(sudo timeshift --list | grep "Device" | awk '{print $NF}')
    sudo timeshift --restore --snapshot "$1" --device $device
}

# A submenu that list all snapshots
snapshot_menu() {

    restore="Restore"
    
    if [ -z "$snapshot" ] ; then
       snapshot=$(echo "$chosen" | awk '{print $3}')
    else
       snapshot=$(echo "$chosen")
    fi

    options="$snapshot\n$divider\n$restore\n$delete\n$goback\n$exit"

    # Open rofi menu, read chosen option
    chosen="$(echo -e "$options" | $rofi_command )"

    check="$snapshot"

    # Match chosen option to command
    case "$chosen" in
        "" | "$divider")
            echo "No option chosen."
            ;;
        "$delete")
            remove=$(echo "$snapshot" | awk '{print $3}')
            delete_snapshot "$remove"
            show_menu
            ;;
        "$restore")
            restore_snapshot
            ;;
        "$check")
            chosen="$check"
            snapshot_menu
            ;;
        "$goback")
            show_menu
            ;;
        "$exit")
            exit
            ;;
    esac
}

# Opens a rofi menu so you can remove the snapshots
# Or restore the snapshot (Not implemented yet)
show_menu() {
    # Get menu options
    snapshot=$(sudo timeshift --list | grep "^[1-9]" | grep -v snapshots)
    create="Create"
    list="List"

    # Options passed to rofi
    options="$snapshot\n$divider\n$create\n$exit"

    # Open rofi menu, read chosen option
    chosen="$(echo -e "$options" | $rofi_command "Timeshift")"
    
    # Exit the menu
    [ "$chosen" = "Exit" ] && exit
    
    # Match chosen option to command
    case "$chosen" in
        "" | "$divider")
            echo "No option chosen."
            ;;
        "$create")
            create_snapshot
            show_menu
            ;;
        "$chosen")
            snapshot_menu
            chosen_snapshot=$(sudo timeshift --list | grep "$chosen")
            ;;
    esac
}

# Rofi command to pipe into, can add any options here
rofi_command=run

case "$1" in
    *)  # Run the main menu 
        show_menu
        ;;
esac
