#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# Name: dm-editconfig
# Description: dmenu script to delete or create snapshots using timeshift
# Author: Karl Fredin


# Source the config file for dmscript
source $HOME/.config/dm-script.conf

# Options you have available
declare -a options=(
"New-snapshot"
"Remove-snapshot")

# Make your choice
choice=$(printf '%s\n' "${options[@]}" | run -p "Timeshift Action:")

[ -z $choice ] && exit

# If you choose an invalid value nothing is gonna happen
[ "$choice" = "New-snapshot" -o "$choice" = "Remove-snapshot" ] || exit

# Runs this statement if you choose to make a new snabshot
if [ $choice = "New-snapshot" ] ; then

    sudo timeshift --create

# Runs this statement if you choose to remove snabshot
elif [ $choice = "Remove-snapshot" ] ; then

    snapshots=$(sudo timeshift --list | grep "^[0-9]" | grep -v snapshot)
    
    choice_snapshot=$(printf '%s\n' "${snapshots[@]}" | run -p "Snapshot to remove" )
    
    [ -z $choice_snapshot ] && exit
    
    snapshot_name=$(echo $choice_snapshot | awk '{print $3}')
    
    sudo timeshift --delete --snapshot "$snapshot_name"

fi
