#!/bin/bash
##____  _                      _
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  <
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
#
# -*- coding: utf-8 -*-
#
# script that easily lets you choose between tmux sessions running on the system

# Source the config file for dmscript
source $HOME/.config/dm-script.conf

TMUX_SESSIONS=$(tmux ls | awk '{print $1}')
NEW_TMUX="New"


# Make your choice
choice=$(printf '%s\n' "$NEW_TMUX" "$TMUX_SESSIONS"  | run -p "Choose TMUX session to open")

[ -z $choice ] && exit

# if you choose to make a new session
if [ "$choice" = "New" ] ; then

$TERM tmux new -t $NAME

else

# run the tmux session in the terminal
$TERM -e tmux attach -t $choice


fi
