#!/bin/bash
##____  _                      _
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  <
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
#
# -*- coding: utf-8 -*-

# Script to connect to a vpn provider

# Source all the configuration
source $HOME/.config/dm-script.conf

# Make your first choice
choice=$(printf '%s\n' "${connect[@]}" | run  -p "Option:" )

# Exit if you dont make a choice
[ -z $choice ] && exit

# Make the action that you did made in $choice
[ "$choice" = "Disconnect" ] && vpn_disconnect
[ "$choice" = "Connect" ] && vpn_connect
[ "$choice" = "Random" ] && vpn_random
[ "$choice" = "Country" ] && choice=$(printf '%s\n' "${options[@]}" |  run -p "Choose Country:" ) && vpn_country
